name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Test
      run: go test -v ./...

  e2e-test:
    name: E2E test
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Resolve dependencies
      working-directory: e2e
      run: npm install

    - name: Launch QBFT network
      working-directory: e2e
      run: make network-qbft CONSENSUS_TYPE=qbft test network-down

    - name: Launch IBFT 2.0 network
      working-directory: e2e
      run: make network-ibft2 CONSENSUS_TYPE=ibft2 test network-down
